BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'architect';
CREATE TABLE IF NOT EXISTS governed_designs(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,owner_id INTEGER NOT NULL REFERENCES users(id),name TEXT NOT NULL,requirements JSONB NOT NULL,site_constraints JSONB NOT NULL,state TEXT NOT NULL DEFAULT 'draft' CHECK(state IN('draft','validated','professional_review','approved','exported')),validation_result JSONB,professional_reviewer_id INTEGER REFERENCES users(id),professional_approval_note TEXT,version INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS governed_design_queue_idx ON governed_designs(tenant_id,state,updated_at);
CREATE TABLE IF NOT EXISTS governed_design_alternatives(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,design_id BIGINT NOT NULL REFERENCES governed_designs(id) ON DELETE RESTRICT,name TEXT NOT NULL,geometry JSONB NOT NULL,quantities JSONB NOT NULL,validation_result JSONB NOT NULL,created_by INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governed_design_events(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,design_id BIGINT NOT NULL REFERENCES governed_designs(id) ON DELETE RESTRICT,actor_id INTEGER NOT NULL REFERENCES users(id),action TEXT NOT NULL,from_state TEXT,to_state TEXT,rationale TEXT,evidence JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS design_provider_outbox(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,provider TEXT NOT NULL CHECK(provider IN('cad_bim','gis','product_catalog','render_worker','object_storage')),design_id BIGINT REFERENCES governed_designs(id) ON DELETE RESTRICT,operation TEXT NOT NULL,payload_reference TEXT NOT NULL,idempotency_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','delivering','delivered','failed','dead_letter')),attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,provider,idempotency_key));
CREATE OR REPLACE FUNCTION reject_design_event_mutation()RETURNS trigger AS $$BEGIN RAISE EXCEPTION 'governed_design_events is append-only';END;$$LANGUAGE plpgsql;DROP TRIGGER IF EXISTS design_events_append_only ON governed_design_events;CREATE TRIGGER design_events_append_only BEFORE UPDATE OR DELETE ON governed_design_events FOR EACH ROW EXECUTE FUNCTION reject_design_event_mutation();
COMMIT;
